apiVersion: v1
kind: Service
metadata:
  name: mocksvc
  labels:
    app: mocksvc
spec:
  type: NodePort
  ports:
  - name: generic-api
    nodePort: 32121
    port: 8090
    targetPort: 8090
  - name: beam-api
    nodePort: 32123
    port: 8080
    targetPort: 8080
  - name: mock-admin
    nodePort: 32122
    port: 7080
    targetPort: 7080
  selector:
    app: aris-mockserver
