apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deploy
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: aris-mockserver
  template:
    metadata:
      labels:
        app: aris-mockserver
    spec:
      containers:
        - name: mockserver
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          volumeMounts: 
            - name: {{ .Values.volumes.mockserverConfigVol.name }}
              mountPath: {{ .Values.volumeMounts.mockserverConfigVol.mountPath }}
          ports:
            - name: beam-api
              containerPort: 8080
            - name: gen-api-port
              containerPort: 8091
            - name: gen-tkn-port
              containerPort: 8090
      volumes:
        - name: {{ .Values.volumes.mockserverConfigVol.name }}
          hostPath:
            path: {{ .Values.volumes.mockserverConfigVol.hostPath }}
            type: Directory 
