apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  labels:
    app: nginx-svc
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 32121
    port: 80
    targetPort: 80
  selector:
    app: hello-world
