apiVersion: v1
kind: Service
metadata:
  name: bridging-svc
  labels:
    app: bridging
spec:
  type: NodePort
  ports:
  - name: generic-api
    nodePort: 32121
    port: 8081
    targetPort: 8081
  - name: server-port
    nodePort: 32123
    port: 8989
    targetPort: 8989
  selector:
    app: bridging
