apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
  name: cassandra
spec:
  clusterIP: None
  ports:
  - port: {{ .Values.service.headless.port }}
  selector:
    app: cassandra