apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
  name: cassandra
spec:
  clusterIP: None
  ports:
  - name: cqlsh
    port: {{ .Values.service.headless.port }}
  - name: jmx
    port: 7199
  selector:
    app: cassandra