apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
provisioner: nfs.csi.k8s.io
reclaimPolicy: {{ .Values.storageClass.nfs.reclaimPolicy }}
allowVolumeExpansion: true
volumeBindingMode: Immediate
parameters:
  server: {{ .Values.nfsServer.ip }}
  share: {{ .Values.nfsServer.sharedFolder }}
mountOptions:
  - nfsvers=4