nfs-storage-class: false

replicaCount: 1

image:
  osShell:
    repository: docker.io/bitnami/os-shell
    pullPolicy: IfNotPresent
    tag: "12-debian-12-r42"
  cassandra:
    repository: docker.io/bitnami/cassandra
    pullPolicy: IfNotPresent
    tag: "5.0"

service:
  headless:
    port: 9042

nfsServer:
  hostname:
  ip: 192.168.30.3
  sharedFolder: /mnt/nfs_share

storageClass:
  nfs:
    reclaimPolicy: Delete